version: '3.8'

services:
  mysql_shop_warehouse:
    image: mysql:8.0
    container_name: mysql_shop_warehouse
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: shop_warehouse
      MYSQL_ROOT_PASSWORD: root
      TZ: Asia/Jakarta
    ports:
      - "3307:3306"   # gunakan port host 3307 agar tidak bentrok dgn MySQL lokal
    volumes:
      - db_spring_app_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  spring_shop_warehouse_app:
    build: .
    container_name: spring_shop_warehouse_app
    depends_on:
      mysql_shop_warehouse:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql_shop_warehouse:3306/shop_warehouse?useSSL=false&allowPublicKeyRetrieval=true&autoReconnect=true&serverTimezone=Asia/Jakarta
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQL8Dialect
      TZ: Asia/Jakarta
    ports:
      - "8080:8080"
    # Tambahkan sedikit delay agar MySQL benar-benar siap
    command: sh -c "sleep 10 && java -jar app.jar"

volumes:
  db_spring_app_data:
