spring.application.name=YBoilerplate
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=user
spring.rabbitmq.password=password
rabbitmq.queue.name=myPrettyQueue
rabbitmq.exchange.name=myPrettyExchange
rabbitmq.routing.key=myPrettyRoutingKey